export const FETCH_PROFILE_UPDATE_REQUEST = 'FETCH_PROFILE_UPDATE_REQUEST';
export const FETCH_PROFILE_UPDATE_SUCCESS = 'FETCH_PROFILE_UPDATE_SUCCESS';
export const FETCH_PROFILE_UPDATE_FAILURE = 'FETCH_PROFILE_UPDATE_FAILURE';