export const FETCH_GET_USER_POSTS_REQUEST = 'FETCH_GET_USER_POSTS_REQUEST';
export const FETCH_GET_USER_POSTS_SUCCESS = 'FETCH_GET_USER_POSTS_SUCCESS';
export const FETCH_GET_USER_POSTS_FAILURE = 'FETCH_GET_USER_POSTS_FAILURE';
