export const FETCH_DELETE_POST_REQUEST = 'FETCH_DELETE_POST_REQUEST';
export const FETCH_DELETE_POST_SUCCESS = 'FETCH_DELETE_POST_SUCCESS';
export const FETCH_DELETE_POST_FAILURE = 'FETCH_DELETE_POST_FAILURE';